#!/usr/bin/env python3
"""Generate ANSWERED.md - the carve answers indexed by the QUESTION they settle.

WHY
---
`SOURCES.md` is keyed by ARTEFACT ("what is in this file"), which is the wrong
key for the failure it should prevent. The failure is re-deriving something
already settled: a whole session went into rediscovering the fault/restart-P
contract that a carve answer had recorded weeks earlier, because nobody could
search for the QUESTION.

So this indexes by question. It reads each CARVE-*.md in this directory and
takes, in order of preference:

  1. an explicit "**Question asked**" line, if the file has one;
  2. otherwise the H1 title, which in practice names the topic.

Files with neither are listed separately as needing a question line - that list
is the working queue, not an error.

Nothing is rewritten. The 39 carve answers are left alone deliberately: a bulk
edit across another repository's files to add front-matter is a large change
for a small gain, and the titles already carry enough to index on.

Usage:  python make-answered-index.py            (writes ANSWERED.md here)
        python make-answered-index.py --check     (exit 1 if ANSWERED.md is stale)
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "ANSWERED.md"

H1 = re.compile(r"^#\s+(.*?)\s*$")
QLINE = re.compile(r"^\*\*Question asked\*\*\s*(?:\(([^)]*)\))?\s*:?\s*(.*)$", re.IGNORECASE)


def harvest(path: Path):
    """Return (question, source) for one carve file."""
    title = None
    with path.open(encoding="utf-8", errors="replace") as fh:
        for i, line in enumerate(fh):
            if i > 40:
                break
            if title is None:
                m = H1.match(line)
                if m:
                    title = m.group(1)
                    continue
            m = QLINE.match(line.strip())
            if m:
                q = (m.group(2) or "").strip()
                if q:
                    return q, "explicit"
    if title:
        # Titles are written as "CARVE ANSWER: <topic>" / "CARVE ANSWER - <topic>".
        t = re.sub(r"^CARVE\s+ANSWER\s*[:\-—]\s*", "", title, flags=re.IGNORECASE).strip()
        return t, "title"
    return None, None


def render(rows, missing):
    out = []
    out.append("# ANSWERED — the carve answers, indexed by QUESTION\n")
    out.append("**GENERATED by `make-answered-index.py`. Do not hand-edit.**\n")
    out.append("`SOURCES.md` is keyed by ARTEFACT, which is the wrong key for the failure that")
    out.append("actually happens: re-deriving something already settled. A whole session went into")
    out.append("rediscovering a fault/restart contract that a carve answer had recorded weeks")
    out.append("earlier, because the question was not searchable. **Search this file before")
    out.append("deriving anything.**\n")
    out.append(f"{len(rows)} answered questions.\n")
    out.append("| The question it settles | Answer file |")
    out.append("|---|---|")
    for q, name in rows:
        out.append(f"| {q} | `{name}` |")
    out.append("")
    if missing:
        out.append("## Needs a question line\n")
        out.append("These have no `**Question asked**` line and no usable title. Add one line to the")
        out.append("top of each and re-run this script - that is the whole fix.\n")
        for name in missing:
            out.append(f"- `{name}`")
        out.append("")
    return "\n".join(out) + "\n"


def main(argv):
    rows, missing = [], []
    for path in sorted(HERE.glob("CARVE-*.md")):
        q, _ = harvest(path)
        if q:
            rows.append((q, path.name))
        else:
            missing.append(path.name)

    text = render(rows, missing)
    if "--check" in argv:
        if not OUT.exists():
            print(f"{OUT.name} does not exist - run this script without --check")
            return 1
        if OUT.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
            print(f"{OUT.name} is stale - re-run this script")
            return 1
        print(f"{OUT.name} is current ({len(rows)} questions, {len(missing)} need a question line)")
        return 0

    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.name}: {len(rows)} questions, {len(missing)} need a question line")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
